export class Feature {
    id: number;
    name: string;
    number: string;
    description: string;
    acc_criteria: string;
    modified_on: string;
    created_on: string;
    closed_on: string;
    isClosed: boolean;
    creater_id: string;
    creator_name: string;
    type_id: string;
    type_name: string;
    team_id: string;
    team_name: string;
    product_id: string;
    product_name: string;
    status_id: string;
    status_name: string;
    increment_id: number;
    increment_name: string;
    increment_number: string;
    ub_value: number;
    time_crit: number;
    risk_red: number;
    job_size: number;
    wsjf: number;
}